use nalgebra::{SMatrix, SVector};

/// Explicit MPC controller derived from the identified second-order transfer function.
///
/// Identified model (sysid CSV, t >= 60 s):
///   G(s) = 10.90 * exp(-5.30 s) / (16119.1 s^2 + 858.3 s + 1)
///   temperature in deci-°C (CSV / 10 = actual °C), power in percent (CSV / 100 = PWM)
///
/// Rescaled to operating units (°C, PWM 0-1):
///   G(s) = 109 * exp(-5.30 s) / (16119.1 s^2 + 858.3 s + 1)
///   DC gain K_dc = 109 °C / PWM
///
/// Discretised with ZOH at Ts = 1 s, then augmented with a 5-sample input
/// delay line to capture the 5.30 s transport delay.  LQR gain K designed
/// with Q = diag(1, 0.01, 0, 0, 0, 0, 0), R = 0.1.
///
/// State vector (deviation from operating point):
///   z = [x1_dev, x2_dev, u[k-1], u[k-2], u[k-3], u[k-4], u[k-5]]
///
///   x1_dev = T - T_ref            (°C)
///   x2_dev = filtered dT/dt       (°C/s, low-pass α=0.2 applied to finite diff)
///   u[k-i] = u(k-i) - u_ss       (PWM deviation, 5-tap shift register)
///
/// Control law (per second):
///   u_ss  = (T_target - T_ambient) / K_dc
///   u_dev = -K_mpc * z
///   u     = clamp(u_ss + u_ff + u_dev, 0, 1)
pub struct ExplicitMpcController {
    /// 7×7 augmented state transition matrix
    a_aug: SMatrix<f32, 7, 7>,
    /// 7×1 input coupling vector
    b_aug: SVector<f32, 7>,
    /// 1×7 LQR gain row vector
    k_mpc: SMatrix<f32, 1, 7>,
    /// 7×1 internal state (deviation from operating point)
    z_state: SVector<f32, 7>,
    /// Previous measured temperature deviation, used for finite-difference dT/dt
    prev_x1_dev: f32,
    /// Steady-state feedforward power needed to maintain target temperature
    u_ss: f32,
    target_temp: f32,
}

impl ExplicitMpcController {
    /// DC gain of G(s) in °C per unit PWM (0-1 scale).
    /// Derived from G(s) = 10.90/(...) with CSV deci-°C → °C (÷10) and
    /// CSV percent → PWM (÷100): K_dc = 10.90 × 10 = 109.
    const K_DC: f32 = 109.0;

    pub fn new(target_temp: f32, ambient_temp: f32) -> Self {
        // ------------------------------------------------------------------
        // A_aug — ZOH-discretised plant (2×2 block) + 5-tap delay line
        // Generated by sim/derive_mpc.py from G(s) at Ts = 1 s.
        //
        // Eigenvalues: 0.99881 (tau≈839 s slow mode)
        //              0.94928 (tau≈19 s  fast mode)
        // ------------------------------------------------------------------
        let ad_11 = 0.9999695244_f32; // slow pole (x1 ← x1)
        let ad_12 = 0.9738325597_f32; // coupling  (x1 ← x2)
        let ad_21 = -0.0000604148_f32; // coupling  (x2 ← x1)
        let ad_22 = 0.9481154825_f32; // fast pole (x2 ← x2)
        // Delayed input drives the plant (column 6 = u[k-5]):
        // B_d = ZOH integral of exp(A_c*t)*B_c, scaled to °C / PWM.
        // Correct values are 10× smaller than the previous implementation
        // (which used deci-°C units instead of °C for the B vector).
        let bd_1 = 0.0033218441_f32; // delayed input → x1  (was 0.033218, 10× too large)
        let bd_2 = 0.0065852156_f32; // delayed input → x2  (was 0.065852, 10× too large)

        let mut a_aug = SMatrix::<f32, 7, 7>::zeros();
        // 2×2 plant dynamics block (rows/cols 0-1)
        a_aug[(0, 0)] = ad_11;
        a_aug[(0, 1)] = ad_12;
        a_aug[(1, 0)] = ad_21;
        a_aug[(1, 1)] = ad_22;
        // Delayed input drives plant: column 6 = u[k-5] after 5 shifts
        a_aug[(0, 6)] = bd_1;
        a_aug[(1, 6)] = bd_2;
        // 5-tap shift register: u[k-i-1] ← u[k-i]
        a_aug[(3, 2)] = 1.0; // u[k-2] ← u[k-1]
        a_aug[(4, 3)] = 1.0; // u[k-3] ← u[k-2]
        a_aug[(5, 4)] = 1.0; // u[k-4] ← u[k-3]
        a_aug[(6, 5)] = 1.0; // u[k-5] ← u[k-4]

        // B_aug: new input deviation enters at z[2] (u[k-1] slot)
        let mut b_aug = SVector::<f32, 7>::zeros();
        b_aug[2] = 1.0;

        // ------------------------------------------------------------------
        // K_mpc — discrete LQR gain from sim/derive_mpc.py
        // Q = diag(1.0, 0.01, 0, 0, 0, 0, 0),  R = 0.1
        // K[1]/K[0] = 10.4  (was 15.0 — the ratio that caused oscillation)
        // ------------------------------------------------------------------
        let k_mpc = SMatrix::<f32, 1, 7>::from_row_slice(&[
            2.9018317_f32,
            30.1675997_f32,
            0.1592982_f32,
            0.1701918_f32,
            0.1805104_f32,
            0.1902829_f32,
            0.1995372_f32,
        ]);

        // Steady-state feedforward: u_ss = ΔT / K_dc
        let u_ss = (target_temp - ambient_temp) / Self::K_DC;

        Self {
            a_aug,
            b_aug,
            k_mpc,
            z_state: SVector::<f32, 7>::zeros(),
            prev_x1_dev: 0.0,
            u_ss,
            target_temp,
        }
    }

    /// Compute the next heater PWM command (0.0–1.0).
    /// Call exactly once per second.
    ///
    /// `current_temp`  — filtered temperature reading in °C
    /// `pump_is_on`    — true when pump is active (adds feedforward load)
    pub fn update(&mut self, current_temp: f32, pump_is_on: bool) -> f32 {
        // ------------------------------------------------------------------
        // Step 1: Inject measured states into the deviation vector
        // ------------------------------------------------------------------
        let x1_dev = current_temp - self.target_temp;

        // Finite-difference derivative using the PREVIOUS MEASURED deviation,
        // not the model-propagated z_state[0] (which would be biased by the
        // model prediction and cause z[1] to drift during transients).
        let raw_x2_dev = x1_dev - self.prev_x1_dev;
        self.prev_x1_dev = x1_dev;

        // Low-pass filter (α=0.2) to suppress 1-Hz sample noise before
        // multiplying by K[1]=30.2 — without filtering even 1-sample
        // noise spikes would produce ±6 PWM units of spurious correction.
        let filtered_x2_dev = 0.8 * self.z_state[1] + 0.2 * raw_x2_dev;

        self.z_state[0] = x1_dev;
        self.z_state[1] = filtered_x2_dev;

        // ------------------------------------------------------------------
        // Step 2: Pump-on feedforward
        // Water flow through the thermoblock creates an additional thermal
        // load.  This value was empirically identified during sysid.
        // ------------------------------------------------------------------
        let u_ff = if pump_is_on { 0.3138 } else { 0.0 };

        // ------------------------------------------------------------------
        // Step 3: LQR feedback  u_dev = -K * z
        // ------------------------------------------------------------------
        let u_dev = -(self.k_mpc * self.z_state)[0];

        // Total command = steady-state bias + pump feedforward + tracking correction
        let u_command = (self.u_ss + u_ff + u_dev).clamp(0.0, 1.0);

        // ------------------------------------------------------------------
        // Step 4: Propagate augmented state
        //   z[k+1] = A_aug * z[k] + B_aug * (u - u_ss)
        // ------------------------------------------------------------------
        let u_input_dev = u_command - self.u_ss;
        self.z_state = (self.a_aug * self.z_state) + (self.b_aug * u_input_dev);

        u_command
    }

    /// Reset internal state to equilibrium (call on heater enable/disable).
    pub fn reset(&mut self) {
        self.z_state = SVector::<f32, 7>::zeros();
        self.prev_x1_dev = 0.0;
    }
}
